# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-IRC
version:      0.2
version_from: IRC.pm
installdirs:  site
requires:
    Carp:                          0
    Date::Format:                  0
    POE:                           0.0607
    POE::Component::Client::DNS:   0
    POE::Component::Client::Ident: 0
    POE::Filter::IRCD:             0
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
